<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicstore [
  
<!ELEMENT musicstore (musicalbum)*>
<!ELEMENT musicalbum (title, artist?, year?, genre?, publisher?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
]>

<musicstore>
	<musicalbum>
		<title> The Black Light </title>
		<artist> Calexico </artist>
		<year> 1998 </year>
		<genre> Roots </genre>
		<publisher> City Slang </publisher>
	</musicalbum>
	
	<musicalbum>
    <title> Μπραζιλέρο </title>
    <artist> Νίκος Πορτοκάλογλου </artist>
    <year> 2001 </year>
    <genre> Alternative </genre>
    <publisher> UMG </publisher>
  </musicalbum>

  <musicalbum>
    <title> Δι'Ευχών </title>
    <artist> Χάρις Αλεξίου </artist>
    <year> 1992 </year>
    <genre> Alternative </genre>
    <publisher> UMG </publisher>
  </musicalbum>
  
  <musicalbum>
	<title> The Good Son </title>
	<artist> Nick Cave and The Bad Seeds </artist>
	<year> 1990 </year>
	<genre> Rock </genre>
	<publisher> Blank </publisher>
  </musicalbum>
  
</musicstore>